server:
  port: 10001
spring:
  devtools:
    restart:
      #热部署生效
      enabled: true
        #设置重启的目录
      #additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
logging:
  #config: logback
  level:
    com.ruiming.logging: error
  #配置日志位置
  file: C:\Users\Administrator\Desktop\demo\6.log
  #配置日志输出格式
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{36} [%line] - %msg%n'