server: 
  port: 10088
spring: 
  application:  
    name: elk-base #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.128:3306/leyou?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 112233
  jpa: 
    database: MySQL
    show-sql: true
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.88.128:9300
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      #additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
